version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch7
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./elasticsearch/config/:/usr/share/elasticsearch/config/
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/logs/:/usr/share/elasticsearch/logs/
    networks:
      - "elk-net"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.1
    container_name: logstash7
    aliases:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/:/usr/share/logstash/config
    networks:
      - "elk-net"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana7
    aliases:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./kibana/config/:/usr/share/kibana/config/
    networks:
      - "elk-net"
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  elk-net:
    driver: bridge